name: test_gen
description: "A CLI tool that generates Dart tests using Gemini AI"
version: 0.1.0
homepage: https://github.com/JayPcloud/test_gen_dart
repository: https://github.com/JayPcloud/test_gen_dart.git

environment:
  sdk: ^3.6.1

# Add regular dependencies here.
dependencies:
  args: ^2.5.0
  google_generative_ai: ^0.4.6
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
